ENH: Fix artifact upload naming conflict
Fix artifact upload naming conflict:
- Add the label of the required version mode to the artifact name.
- Pin action version.

In v4, artifacts are immutable (unless deleted), so each of the uploaded
artifacts needs to have a different name.

Fixes:
```
Error: Failed to CreateArtifact: Received non-retryable error:
Failed request: (409) Conflict:
an artifact with this name already exists on the workflow run
```

raised for example in
https://github.com/SlicerDMRI/whitematteranalysis/actions/runs/7407939750