BUG: Import `joblib` modules in cluster outlier removal script
Import `joblib` modules in cluster outlier removal script.

Fixes:
```
File /bin/wm_cluster_remove_outliers.py, line 256, in main
  logtrs = Parallel(n_jobs=number_of_jobs, verbose=0)(
NameError: name 'Parallel' is not defined
```

Inadvertently removed in commit f66b337.