ENH: Fix `pandas` version to 2.0.3 (#145)
* ENH: Fix `pandas` version to 2.0.3

Fix `pandas` version to 2.0.3, which is the last version known to be
working.

Fixes:
```
Searching for pandas>=0.19
Reading https://pypi.org/simple/pandas/
Downloading
https://files.pythonhosted.org/packages/a9/ec/
e531733ff7f955e58ac45089cf72d085e587a731778b9dac1b82878815e9/
pandas-2.1.0rc0.tar.gz#sha256=e6967a82ee26997ab5ef52907064ca21eed5e51089dc2131a252a26d67d88b36
Best match: pandas 2.1.0rc0
Processing pandas-2.1.0rc0.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-xxw2q3r_/pandas-2.1.0rc0.tar.gz
Error: Process completed with exit code 1.
```

raised for example in:
https://github.com/SlicerDMRI/whitematteranalysis/actions/runs/5965246190/job/16182228792#step:5:464

* ENH: Allow the test, package GHA workflow to run on pull requests

Allow the test, package GHA workflow to run on pull requests.